apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db  # Mount persistent volume for data storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-storage  # Reference to the PersistentVolumeClaim defined below
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017  # Expose MongoDB for external access if needed
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
spec:
  accessModes:
    - ReadWriteOnce  # Allows the volume to be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi  # Allocate 1Gi storage for MongoDB data
